In [30]:

import pandas as pd
import numpy as np
import math


df = pd.read_csv("/home/jovyan/ODBiz/5a-Matching/output/matched.csv", low_memory=False)

# STEP 1
# copy over NAICS values that already exist in the data


# This fills all the null values in the columns with 10 for analysis
#df.primary_NAICS.fillna(value=10, inplace=True)



df['NAICS_Group'] = df.primary_NAICS.astype(str).str[:2]


# returns the 10 values back to null
#df['primary_NAICS'] = df['primary_NAICS'].replace(10, '')
df['NAICS_Group'] = df['NAICS_Group'].replace('na', np.nan)


# STEP 2
# find the NAICS numbers that
# were put in business_sector column


agri = '11'
mining = '21'
uti = '22'
cons = '23'
mani = '31-33'
whole = '41'
retail = '44-45'
trans = '48-49'
info = '51'
fin = '52'
real = '53'
prof = '54'
mang = '55'
admin = '56'
edu = '61'
health = '62'
arts = '71'
acco = '72'
other = '81'
pub = '91'


df.loc[df['business_sector'].str.contains(agri, case= False, na= False), 'NAICS_Group']= 11.0
df.loc[df['business_sector'].str.contains(mining, case = False, na = False), 'NAICS_Group' ] = 21.0
df.loc[df['business_sector'].str.contains(uti, case = False, na = False), 'NAICS_Group' ] = 22.0
df.loc[df['business_sector'].str.contains(cons, case = False, na = False), 'NAICS_Group' ] = 23.0
df.loc[df['business_sector'].str.contains(mani, case = False, na = False), 'NAICS_Group' ] = 31.0
df.loc[df['business_sector'].str.contains(whole, case = False, na = False), 'NAICS_Group' ] = 41.0
df.loc[df['business_sector'].str.contains(retail, case = False, na = False), 'NAICS_Group' ] = 44.0
df.loc[df['business_sector'].str.contains(trans, case = False, na = False), 'NAICS_Group' ] = 48.0
df.loc[df['business_sector'].str.contains(info, case = False, na = False), 'NAICS_Group' ] = 51.0
df.loc[df['business_sector'].str.contains(fin, case = False, na = False), 'NAICS_Group' ] = 52.0
df.loc[df['business_sector'].str.contains(real, case = False, na = False), 'NAICS_Group' ] = 53.0
df.loc[df['business_sector'].str.contains(prof, case = False, na = False), 'NAICS_Group' ] = 54.0
df.loc[df['business_sector'].str.contains(mang, case = False, na = False), 'NAICS_Group' ] = 55.0
df.loc[df['business_sector'].str.contains(admin, case = False, na = False), 'NAICS_Group' ] = 56.0
df.loc[df['business_sector'].str.contains(edu, case = False, na = False), 'NAICS_Group' ] = 61.0
df.loc[df['business_sector'].str.contains(health, case = False, na = False), 'NAICS_Group' ] = 62.0
df.loc[df['business_sector'].str.contains(arts, case = False, na = False), 'NAICS_Group' ] = 71.0
df.loc[df['business_sector'].str.contains(acco, case = False, na = False), 'NAICS_Group' ] = 72.0
df.loc[df['business_sector'].str.contains(other, case = False, na = False), 'NAICS_Group' ] = 81.0
df.loc[df['business_sector'].str.contains(pub, case = False, na = False), 'NAICS_Group' ] = 91.0



df.to_csv('/home/jovyan/ODBiz/8-Analysis/1PLA.csv', index=False)

In [31]:
# STEP 3
# - find the the EXACT NAICS description
# that is in the business
# description column
# - we fill the empty values
# in our new NAICS_Group column in
# with the buisness description values
# - split business description by the deliminator '/'
# and keep the first part to use for an exact key-phrase match


df['NAICS_Group'].fillna(df.business_description.str.split('/').str[0], inplace= True)



agri = '(Agriculture, forestry, fishing & hunting)'
mining = '(Mining, quarrying, & oil & gas extraction)'
uti = '(Utilities)'
cons = '(Construction)'
manu = '(Manufacturing)'
whole = '(Wholesale trade)'
retail = "(Retail trade)"
trans = '(Transportation & warehousing)'
info = '(Information & cultural industries)'
fin = '(Finance & insurance)'
real = '(Real estate & rental & leasing)'
prof = '(Professional, scientific & technical services)'
mang = '(Management of companies & enterprises)'
admin = '(Administrative & support, waste management & remediation services)|(Admin. support waste mgmt & remed. services)|(Admin., support, waste mgmt & remed. services )'
edu = '(Educational services)'
health = '(Health care & social assistance)'
arts = '(Arts, entertainment & recreation)'
acco = '(Accommodation & food services)'
other = '(Other services \(exc. Public administration\))'
pub = '(Public administration)'


df.loc[df['NAICS_Group'].str.match(agri, case= False, na= False), 'NAICS_Group'] = 11.0
df.loc[df['NAICS_Group'].str.match(mining, case= False, na= False), 'NAICS_Group'] = 21.0
df.loc[df['NAICS_Group'].str.match(uti, case= False, na= False), 'NAICS_Group'] = 22.0
df.loc[df['NAICS_Group'].str.match(cons, case= False, na= False), 'NAICS_Group'] = 23.0
df.loc[df['NAICS_Group'].str.match(manu, case= False, na= False), 'NAICS_Group'] = 31.0
df.loc[df['NAICS_Group'].str.match(whole, case= False, na= False), 'NAICS_Group'] = 41.0
df.loc[df['NAICS_Group'].str.match(retail, case= False, na= False), 'NAICS_Group'] = 44.0
df.loc[df['NAICS_Group'].str.match(trans, case= False, na= False), 'NAICS_Group'] = 48.0
df.loc[df['NAICS_Group'].str.match(info, case= False, na= False), 'NAICS_Group'] = 51.0
df.loc[df['NAICS_Group'].str.match(fin, case= False, na= False), 'NAICS_Group'] = 52.0
df.loc[df['NAICS_Group'].str.match(real, case= False, na= False), 'NAICS_Group'] = 53.0
df.loc[df['NAICS_Group'].str.match(prof, case= False, na= False), 'NAICS_Group'] = 54.0
df.loc[df['NAICS_Group'].str.match(mang, case= False, na= False), 'NAICS_Group'] = 55.0
df.loc[df['NAICS_Group'].str.match(admin, case= False, na= False), 'NAICS_Group'] = 56.0
df.loc[df['NAICS_Group'].str.match(edu, case= False, na= False), 'NAICS_Group'] = 61.0
df.loc[df['NAICS_Group'].str.match(health, case= False, na= False), 'NAICS_Group'] = 62.0
df.loc[df['NAICS_Group'].str.match(arts, case= False, na= False), 'NAICS_Group'] = 71.0
df.loc[df['NAICS_Group'].str.match(acco, case= False, na= False), 'NAICS_Group'] = 72.0
df.loc[df['NAICS_Group'].str.match(other, case= False, na= False), 'NAICS_Group'] = 81.0
df.loc[df['NAICS_Group'].str.match(pub, case= False, na= False), 'NAICS_Group'] = 91.0




df.to_csv('/home/jovyan/ODBiz/8-Analysis/1PLA.csv', index=False)

In [32]:
# STEP 4
# - we are now going to copy all
# the NAICS values that we have
# found into a seperate column
# because we know they are
# the for sure accurate ones
# - also going to get rid of
# anything that is not a number


df['NAICS'] = df['NAICS_Group']

df['NAICS'] = (pd.to_numeric(df['NAICS'], errors= 'coerce').fillna(''))


df.to_csv('/home/jovyan/ODBiz/8-Analysis/1PLA.csv', index=False)

In [33]:
# STEP 5
# in the empty fields that are
# left in our NAICS_Group column
# fill in values from subsector,
# sector and licence type (in that order)


df['NAICS_Group'].fillna(df['business_subsector'], inplace= True)
df['NAICS_Group'].fillna(df['business_sector'], inplace= True)
df['NAICS_Group'].fillna(df['licence_type'], inplace= True)




df.to_csv('/home/jovyan/ODBiz/8-Analysis/1PLA.csv', index=False)

In [34]:
# STEP 6
# using keywords fill in
# the rest of the cells with
# the corresponding code
# (least accurate/ still de-bugging)


agri = 'agriculture'
mining = 'mining'
uti = 'utilities'
cons = 'construction|building|contractors|cement|contractor|ecavating|excavating|excavation|installation'
mani = 'manifacturing|manufacturer|Manufacturing|mfg.|printing|printer|Manufacturer'
whole = 'wholesale|whlse.'
retail = 'retail|store|supplies|clothing|sales|dealer|pharmacy'
trans = 'transportation|courier|warehouse|warehousing|trucking'
info = 'information|publishing|animation|production'
fin = 'finance|bank|bookkeeping|broker|financial|currency|credit|insurance|investment'
real = 'apartment|property|hall|real|property'
prof = 'accountant|veterinarian|research|lawyer|law|advertising|architect|consulting|consultant|agent|counselling|publisher|design|development|engineer|solicitor|graphic'
mang = 'enterprises|Management'
admin = 'waste|administration|agency|cleaning|janitorial|security'
edu = 'educational|education|instruction|tutor|school|schools|training|teacher|tutoring'
health = 'health|Psychiatrist|pathologist|Therapies|therapy|Oculist|acupuncturist|chiropractor|dentist|clinic|denturist|Psychologist|doctor|RMT|pediatric|hospital|therapist|laboratory|physician|dental|psychological|Podiatrist|GASTROENTEROLOGIST|Physiotherapy|Optometrist'
arts = 'arts|studio|dance|entertainment|event|fitness|film|photographer'
acco = 'accommodation|restaurant|cafe|caterer|casino|dining|food|hotel|Bed and Breakfast|Restaurant|patio|liquor'
other = 'Auto|barber|beauty|repair|charitable|charity|association|spa|dating|Esthetician|personal|hairdresser|hairdressing|hair|massage'
pub = 'public'


df.loc[df['NAICS_Group'].str.contains(agri, case= False, na= False), 'NAICS_Group']= 11.0
df.loc[df['NAICS_Group'].str.contains(mining, case= False, na= False), 'NAICS_Group']= 21.0
df.loc[df['NAICS_Group'].str.contains(uti, case= False, na= False), 'NAICS_Group']= 22.0
df.loc[df['NAICS_Group'].str.contains(cons, case= False, na= False), 'NAICS_Group']= 23.0
df.loc[df['NAICS_Group'].str.contains(mani, case= False, na= False), 'NAICS_Group']= 31.0
df.loc[df['NAICS_Group'].str.contains(whole, case= False, na= False), 'NAICS_Group']= 41.0
df.loc[df['NAICS_Group'].str.contains(retail, case= False, na= False), 'NAICS_Group']= 44.0
df.loc[df['NAICS_Group'].str.contains(trans, case= False, na= False), 'NAICS_Group']= 48.0
df.loc[df['NAICS_Group'].str.contains(info, case= False, na= False), 'NAICS_Group']= 51.0
df.loc[df['NAICS_Group'].str.contains(fin, case= False, na= False), 'NAICS_Group']= 52.0
df.loc[df['NAICS_Group'].str.contains(real, case= False, na= False), 'NAICS_Group']= 53.0
df.loc[df['NAICS_Group'].str.contains(prof, case= False, na= False), 'NAICS_Group']= 54.0
df.loc[df['NAICS_Group'].str.contains(mang, case= False, na= False), 'NAICS_Group']= 55.0
df.loc[df['NAICS_Group'].str.contains(admin, case= False, na= False), 'NAICS_Group']= 56.0
df.loc[df['NAICS_Group'].str.contains(edu, case= False, na= False), 'NAICS_Group']= 61.0
df.loc[df['NAICS_Group'].str.contains(health, case= False, na= False), 'NAICS_Group']= 62.0
df.loc[df['NAICS_Group'].str.contains(arts, case= False, na= False), 'NAICS_Group']= 71.0
df.loc[df['NAICS_Group'].str.contains(acco, case= False, na= False), 'NAICS_Group']= 72.0
df.loc[df['NAICS_Group'].str.contains(other, case= False, na= False), 'NAICS_Group']= 81.0
df.loc[df['NAICS_Group'].str.contains(pub, case= False, na= False), 'NAICS_Group']= 91.0



df.to_csv('/home/jovyan/ODBiz/8-Analysis/1PLA.csv', index=False)

In [35]:

# STEP 6
# - we are now going to copy all
# the NAICS values that we have
# found into a seperate column
# because we know they are
# the for sure accurate ones
# - also going to get rid of
# anything that is not a number


df['NAICS_total'] = df['NAICS_Group']

df['NAICS_total'] = (pd.to_numeric(df['NAICS_total'], errors= 'coerce').fillna(''))


df.to_csv('/home/jovyan/ODBiz/8-Analysis/1PLA.csv', index=False)

In [38]:
import pandas as pd
import numpy as np
import math


data_2 = pd.read_csv('/home/jovyan/ODBiz/8-Analysis/1PLA.csv', low_memory=False)





# how many total rows there are
count_unique_idx = data_2['idx'].nunique()     
print(f' There are a total of {count_unique_idx} unique rows in this dataset')



#how many total unique rows in naics_group
count_unique_naics = data_2['NAICS_total'].nunique()   
print(f' unique rows in {count_unique_naics} NAICS_Total ')




#how many total businesses by province
group_prov_idx = data_2.groupby('province')['idx'].count() 
print('how many total businesses by province')
print(group_prov_idx)




#how many provinces by naics groups (this is Total NAICS)
group_prov_naics = data_2.groupby('province')['NAICS_total'].count() 
print('How many provinces for total NAICS')
print(group_prov_naics)





#how many provinces by naics (this is Accurate NAICS)
group_naics =data_2.groupby('province')['NAICS'].count()
print(group_naics)



# How many Accurate NAICS codes by province
group_naics_prov =data_2.groupby('NAICS')['province'].count()
print(group_naics_prov)


# How many Total NAICS codes by province
group_naics_group_prov =data_2.groupby('NAICS_total')['province'].count()
print(group_naics_group_prov)

 There are a total of 803491 unique rows in this dataset
30
province
78                       1
AB                   77097
BC                  232465
LAKEVIEW ESTATES         1
MB                     224
NB                     155
NL                      33
NS                      46
NT                    1563
NU                     223
ON                  243590
PE                       5
QC                  244527
SK                     168
YT                      13
Name: idx, dtype: int64
province
78                       1
AB                   65432
BC                  173081
LAKEVIEW ESTATES         1
MB                     206
NB                     106
NL                      30
NS                      45
NT                     873
NU                      50
ON                  155654
PE                       5
QC                    6794
SK                     153
YT                      10
Name: NAICS_total, dtype: int64
province
78                      0
AB                   2615
BC                  38896
LAKEVIEW ESTATES        0
MB                    158
NB                     31
NL                     28
NS                     35
NT                     99
NU                     48
ON                  82148
PE                      3
QC                    276
SK                    110
YT                      6
Name: NAICS, dtype: int64
NAICS
0.0       110
1.0        16
11.0     1154
21.0      170
22.0      162
23.0    10392
31.0     1585
32.0     2505
33.0     4748
41.0     7617
42.0       27
44.0    14876
45.0     4011
48.0     2558
49.0     1018
51.0     1362
52.0     4088
53.0     4635
54.0    12302
55.0      558
56.0     5306
61.0     4220
62.0    12136
71.0     2542
72.0    10774
81.0    14893
91.0      687
99.0        1
Name: province, dtype: int64
NAICS_total
0.0         110
1.0          16
11.0       1214
21.0       1080
22.0        175
23.0      60697
31.0       6447
32.0       2505
33.0       4748
41.0      13812
42.0         27
44.0      73641
45.0       4011
48.0       5054
49.0       1018
51.0       3775
52.0       8544
53.0      17496
54.0      34810
55.0       1522
56.0      12021
61.0       9549
62.0      21635
71.0       7078
72.0      49281
81.0      47860
91.0      14312
99.0          1
3199.0        1
7799.0        1
Name: province, dtype: int64

In [7]:
import pandas as pd
import numpy as np
import math


df = pd.read_csv('/home/jovyan/ODBiz/8-Analysis/1PLA.csv', low_memory=False)



df2 =  df[np.isnan(df['NAICS_total'])]


df2.to_csv('/home/jovyan/ODBiz/8-Analysis/2PLA.csv', index=False)

In [11]:



# how many total rows there are
count_unique_idx = df2['idx'].nunique()     
print(f' There are a total of {count_unique_idx} unique rows in this dataset')



# how many total rows of the business_sector are there
sector = df2['business_sector'].nunique()     
print(f' business_sector information count is  {sector}')



# how many total rows there are
subsector = df2['business_subsector'].nunique()     
print(f' business_subsector info count is  {subsector} ')




# how many total rows there are
description = df2['business_description'].nunique()     
print(f' business_description info is {description} ')




# how many total rows there are
licence = df2['licence_type'].nunique()     
print(f' licence_type infor is {licence} ')

 There are a total of 397689 unique rows in this dataset
 business_sector information count is  20670
 business_subsector info count is  2045
 business_description info is 3769
 licence_type infor is 89

In [ ]:
numb = [ 11.0,       
21.0,       
22.0,        
23.0,      
31.0,       
32.0,       
33.0,       
41.0,      
42.0,        
44.0,      
45.0,      
48.0,      
49.0,       
51.0,       
52.0,       
53.0,      
54.0,     
55.0,       
56.0,      
61.0,      
62.0,      
71.0,       
72.0,      
81.0,      
91.0,     
99.0,         
3199.0,       
7799.0 ]